kind: pipeline
type: docker
name: default

steps:
  - name: kops_infra
    image: turik207/kops:1.23.2.6
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    
    commands:
      - export $keyid
      - export $key
      - kops version
      - kops create cluster --name cluster.turali7v.click --zones eu-central-1a --state s3://kube-tismov-bt --yes
      - kops validate cluster --state=s3://kube-tismov-bt --wait 10m
      - cat $HOME/.kube/config
      - cat $HOME/.kube/config > file
      - ls -l

  - name: kubectl
    image: bitnami/kubectl:latest
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    
    commands:
      - export $keyid
      - export $key
      - kubectl get nodes
