kind: pipeline
type: docker
name: default

steps:

  - name: create file
    image: turik207/kubectl:1.23
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    commands:
      - pwd
      - echo "Hello from first step" > step1
      - kubectl version --client
      - ls -al

  - name: copy file to aws s3
    image: amazon/aws-cli
    environment:
      keyid:
        from_secret: accesskey
      key:
        from_secret: secretkey
    commands:
      - export $accesskey
      - export $secretkey
      - aws --version
      - ls -al
      - aws s3 ls k8s-kubeconfig-i7v
      - aws s3 cp step1 s3://k8s-kubeconfig-i7v/
         
  - name: show files in bucket
    image: amazon/aws-cli
    environment:
      keyid:
        from_secret: accesskey
      key:
        from_secret: secretkey
    commands:
      - ls -l
      
#   - name: upload
#     image: plugins/s3
#     settings:
#       bucket: k8s-kubeconfig-i7v
#       region: eu-central-1
#       access_key:
#         from_secret: accesskey
#       secret_key: 
#         from_secret: secretkey
#       source: config
#       target: /


#   - name: istioctl
#     image: turik207/istio:1.14
#     environment:
#       keyid:
#         from_secret: keyid
#       key:
#         from_secret: key
#     commands:
#       - export $keyid
#       - export $key
#       - cp -r config HOME/.kube/
#       - kubectl get nodes
#       - istioctl version
