kind: pipeline
type: docker
name: default
steps:
  - name: deploy_infra
    image: bitnami/kubectl:latest
     
    commands:
      - echo "Hello world"
      - curl google.com
      - pwd
      - touch /tmp/test.yaml
      - cp /tmp/test.yaml ./
      - ls ./
      - eksctl version
