kind: pipeline
type: docker
name: default

steps:
  - name: deploy_infra
    image: turik207/kops:1.23.2.5
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    
    commands:
      - export $keyid
      - export $key
      - kops version
      - kops create cluster --name cluster.turali7v.click --zones eu-central-1a --state s3://kube-tismov-bt --yes
