kind: pipeline
type: docker
name: default

steps:

#   - name: test
#     image: turik207/kubectl:1.23
#     environment:
#       keyid:
#         from_secret: keyid
#       key:
#         from_secret: key
#     commands:
#       - pwd
#       - echo "Hello from first step" > step1
#       - kubectl version --client
      
  - name: kops_infra
    image: turik207/kops:1.23.2.7
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    commands:
      - export $keyid
      - export $key
      # - kops create cluster --name cluster.turali7v.click --zones eu-central-1a --state s3://kube-tismov-bt --yes
      # - kops validate cluster --state=s3://kube-tismov-bt --wait 10m
#       - cat $HOME/.kube/config
#       - cat $HOME/.kube/config > config
      - echo "this is config file" > config
      - ls -l
      
  - name: upload
    image: plugins/s3
    settings:
      bucket: k8s-kubeconfig-i7v
      region: eu-central-1
      access_key:
        from_secret: accesskey
      secret_key: 
        from_secret: secretkey
      source: config
      target: /


#   - name: istioctl
#     image: turik207/istio:1.14
#     environment:
#       keyid:
#         from_secret: keyid
#       key:
#         from_secret: key
#     commands:
#       - export $keyid
#       - export $key
#       - cp -r config HOME/.kube/
#       - kubectl get nodes
#       - istioctl version
