kind: pipeline
type: docker
name: default

steps:
  - name: deploy_infra
    image: turik207/eksctl:0.103.0
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    
    commands:
      - export $keyid
      - export $key
      - eksctl version
      - eksctl create cluster -f eksctl-cluster.yml
