apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : my-cluster
  region: eu-central-1



nodeGroups:
  - name             : node1
    instanceType     : t3.small
    desiredCapacity  : 1
  - name             : node2
    instanceType     : t3.small
    desiredCapacity  : 1
  
password:
  - password:qwerty123
  - secret: tural123!#!
  
key:
  - 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
